/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cryptocast_crypto_IntegersModuloPrime */

#ifndef _Included_cryptocast_crypto_IntegersModuloPrime
#define _Included_cryptocast_crypto_IntegersModuloPrime
#ifdef __cplusplus
extern "C" {
#endif
#undef cryptocast_crypto_IntegersModuloPrime_serialVersionUID
#define cryptocast_crypto_IntegersModuloPrime_serialVersionUID -5044040558567213861LL
#undef cryptocast_crypto_IntegersModuloPrime_serialVersionUID
#define cryptocast_crypto_IntegersModuloPrime_serialVersionUID -2607220779180962188LL
/*
 * Class:     cryptocast_crypto_IntegersModuloPrime
 * Method:    nativeModPow
 * Signature: ([B[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_cryptocast_crypto_IntegersModuloPrime_nativeModPow
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
