/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cryptocast_crypto_LagrangeInterpolation */

#ifndef _Included_cryptocast_crypto_LagrangeInterpolation
#define _Included_cryptocast_crypto_LagrangeInterpolation
#ifdef __cplusplus
extern "C" {
#endif
#undef cryptocast_crypto_LagrangeInterpolation_serialVersionUID
#define cryptocast_crypto_LagrangeInterpolation_serialVersionUID 4096286734152138209LL
/*
 * Class:     cryptocast_crypto_LagrangeInterpolation
 * Method:    nativeComputeCoefficients
 * Signature: ([[B[B)[[B
 */
JNIEXPORT jobjectArray JNICALL Java_cryptocast_crypto_LagrangeInterpolation_nativeComputeCoefficients
  (JNIEnv *, jclass, jobjectArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
