/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cryptocast_crypto_PolynomialMultiEvaluation */

#ifndef _Included_cryptocast_crypto_PolynomialMultiEvaluation
#define _Included_cryptocast_crypto_PolynomialMultiEvaluation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cryptocast_crypto_PolynomialMultiEvaluation
 * Method:    nativeMultiEval
 * Signature: ([[B[[B[B)[[B
 */
JNIEXPORT jobjectArray JNICALL Java_cryptocast_crypto_PolynomialMultiEvaluation_nativeMultiEval
  (JNIEnv *, jclass, jobjectArray, jobjectArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
